*
* $Id: eva1.inc 220 2007-11-19 16:08:06Z rdm $
*
* $Log: eva1.inc,v $
* Revision 1.1.1.1  2002/06/16 15:18:38  hristov
* Separate distribution  of Geant3
*
* Revision 1.1.1.1  1999/05/18 15:55:16  fca
* AliRoot sources
*
* Revision 1.1.1.1  1995/10/24 10:20:38  cernlib
* Geant
*
*
#ifndef CERNLIB_GEANT321_EVA1_INC
#define CERNLIB_GEANT321_EVA1_INC
*
*
* eva1.inc
*
*                                                                      *
*=== eva1 =============================================================*
*                                                                      *
      COMMON /FKEVA1/ NPART(6),EPART(100,6),COSEVP(3,100,6),HEVSUM
 

#endif
