*
* $Id: gcdlin.inc 220 2007-11-19 16:08:06Z rdm $
*
* $Log: gcdlin.inc,v $
* Revision 1.1.1.1  2002/06/16 15:18:38  hristov
* Separate distribution  of Geant3
*
* Revision 1.1.1.1  1999/05/18 15:55:16  fca
* AliRoot sources
*
* Revision 1.1.1.1  1995/10/24 10:20:42  cernlib
* Geant
*
*
#ifndef CERNLIB_GEANT321_GCDLIN_INC
#define CERNLIB_GEANT321_GCDLIN_INC
*
*
* gcdlin.inc
*
      COMMON/GCDLIN/NCWORD(2),JCADNT,JBUF1,JBUF2
      EQUIVALENCE (JBUF1,JCDLST),(JCADNT,JCDFRS)
*

#endif
