*
* $Id: gthiln.inc 220 2007-11-19 16:08:06Z rdm $
*
* $Log: gthiln.inc,v $
* Revision 1.1.1.1  2002/06/16 15:18:38  hristov
* Separate distribution  of Geant3
*
* Revision 1.1.1.1  1999/05/18 15:55:16  fca
* AliRoot sources
*
* Revision 1.1.1.1  1995/10/24 10:20:34  cernlib
* Geant
*
*
#ifndef CERNLIB_GEANT321_GTHILN_INC
#define CERNLIB_GEANT321_GTHILN_INC
*
*
* gthiln.inc
*
#if !defined(CERNLIB_INCLUDE)
      INTEGER LARECG,JCGOBJ,JCGCOL,JCOUNT,JCLIPS,IMPOIN,IMCOUN,
     +        JSIX,JSIY,JSIZ,JPXC,JPYC,JPZC,ICLIP1,ICLIP2
#endif

#endif
