*
* $Id: gtlist.inc 220 2007-11-19 16:08:06Z rdm $
*
* $Log: gtlist.inc,v $
* Revision 1.1.1.1  2002/06/16 15:18:38  hristov
* Separate distribution  of Geant3
*
* Revision 1.1.1.1  1999/05/18 15:55:16  fca
* AliRoot sources
*
* Revision 1.1.1.1  1995/10/24 10:20:32  cernlib
* Geant
*
*
#ifndef CERNLIB_GEANT321_GTLIST_INC
#define CERNLIB_GEANT321_GTLIST_INC
*
*
* gtlist.inc
*
#if !defined(CERNLIB_INCLUDE)
      INTEGER       NHSTA,NGET ,NSAVE,NSETS,NPRIN,NGEOM,NVIEW,NPLOT
     + ,NSTAT,LHSTA,LGET ,LSAVE,LSETS,LPRIN,LGEOM,LVIEW,LPLOT,LSTAT
C
#endif

#endif
