*
* $Id: gtnum.inc 220 2007-11-19 16:08:06Z rdm $
*
* $Log: gtnum.inc,v $
* Revision 1.1.1.1  2002/06/16 15:18:38  hristov
* Separate distribution  of Geant3
*
* Revision 1.1.1.1  1999/05/18 15:55:16  fca
* AliRoot sources
*
* Revision 1.1.1.1  1995/10/24 10:20:32  cernlib
* Geant
*
*
#ifndef CERNLIB_GEANT321_GTNUM_INC
#define CERNLIB_GEANT321_GTNUM_INC
*
*
* gtnum.inc
*
#if !defined(CERNLIB_INCLUDE)
      INTEGER      NMATE ,NVOLUM,NROTM,NTMED,NTMULT,NTRACK,NPART
     +            ,NSTMAX,NVERTX,NHEAD,NBIT ,NALIVE,NTMSTO
C
#endif

#endif
