*
* $Id: gtstak.inc 220 2007-11-19 16:08:06Z rdm $
*
* $Log: gtstak.inc,v $
* Revision 1.1.1.1  2002/06/16 15:18:38  hristov
* Separate distribution  of Geant3
*
* Revision 1.1.1.1  1999/05/18 15:55:16  fca
* AliRoot sources
*
* Revision 1.1.1.1  1995/10/24 10:20:33  cernlib
* Geant
*
*
#ifndef CERNLIB_GEANT321_GTSTAK_INC
#define CERNLIB_GEANT321_GTSTAK_INC
*
*
* gtstak.inc
*
#if !defined(CERNLIB_INCLUDE)
      INTEGER  NJTMAX,NJTMIN,NTSTKP,NTSTKS,NDBOOK,NDPUSH,NJFREE,NJGARB,
     +         NJINVO,LINSAV,LMXSAV,NWSTAK,NWINT,NWREAL,NWTRAC
      INTEGER ISTORD
#endif

#endif
