*
* $Id: inpdat.inc 220 2007-11-19 16:08:06Z rdm $
*
* $Log: inpdat.inc,v $
* Revision 1.1.1.1  2002/06/16 15:18:38  hristov
* Separate distribution  of Geant3
*
* Revision 1.1.1.1  1999/05/18 15:55:16  fca
* AliRoot sources
*
* Revision 1.1.1.1  1995/10/24 10:20:40  cernlib
* Geant
*
*
#ifndef CERNLIB_GEANT321_INPDAT_INC
#define CERNLIB_GEANT321_INPDAT_INC
*
*
* inpdat.inc
*
*
*=== inpdat ===========================================================*
*
*----------------------------------------------------------------------*
*     include file: inpdat copy          Created 22/12/86 by PA Aarnio
*     changes: revised 29/3/90 by A. Ferrari
*     included in the following subroutines or functions: not updated
*
*     N O W   T H E R E   I S   A   C O P Y   O F   I N P D A T
*     (  I N P D A T 2  )   C R E A T E D
*     T O   A V O I D   T O   D I R T Y   T H E   B A M J E T
*     P A R A M E T E R S !!!!!!!!!!!!
*
*     description of the common block(s) and variable(s)
*
*----------------------------------------------------------------------*
*
      COMMON /FKINPD/ A1, B1, B2, B3, BET, AS, B8, AME, DIQ, IMPS(6,6),
     &                IMVE(6,6),  IB08(6,21), IB10(6,21), IA08(6,21),
     &                IA10(6,21), LT, LE, ISU
 

#endif
