*
* $Id: mconst.inc 220 2007-11-19 16:08:06Z rdm $
*
* $Log: mconst.inc,v $
* Revision 1.1.1.1  2002/06/16 15:18:38  hristov
* Separate distribution  of Geant3
*
* Revision 1.1.1.1  1999/05/18 15:55:16  fca
* AliRoot sources
*
* Revision 1.1.1.1  1995/10/24 10:20:44  cernlib
* Geant
*
*
#ifndef CERNLIB_GEANT321_MCONST_INC
#define CERNLIB_GEANT321_MCONST_INC
*
*
* mconst.inc
*
#include "geant321/mparam.inc"
      COMMON/MCONST/NNR,NQ,NGR,NTSTW,MGPREG,MGP1,M1M,NI,NNUC,NCOL

#endif
