*
* $Id: part2t.inc 220 2007-11-19 16:08:06Z rdm $
*
* $Log: part2t.inc,v $
* Revision 1.1.1.1  2002/06/16 15:18:38  hristov
* Separate distribution  of Geant3
*
* Revision 1.1.1.1  1999/05/18 15:55:17  fca
* AliRoot sources
*
* Revision 1.1.1.1  1995/10/24 10:20:42  cernlib
* Geant
*
*
#ifndef CERNLIB_GEANT321_PART2T_INC
#define CERNLIB_GEANT321_PART2T_INC
*
*
* part2t.inc
*
      DOUBLE PRECISION AAM, GA, TAU, AAMDSC
 

#endif
