*
* $Id: s_defcom.inc 220 2007-11-19 16:08:06Z rdm $
*
* $Log: s_defcom.inc,v $
* Revision 1.1.1.1  2002/06/16 15:18:38  hristov
* Separate distribution  of Geant3
*
* Revision 1.1.1.1  1999/05/18 15:55:17  fca
* AliRoot sources
*
* Revision 1.1.1.1  1995/10/24 10:20:43  cernlib
* Geant
*
*
#ifndef CERNLIB_GEANT321_S_DEFCOM_INC
#define CERNLIB_GEANT321_S_DEFCOM_INC
*
*
* s_defcom.inc
*
#include "geant321/mxgkgh.inc"
#include "geant321/s_consts.inc"
#include "geant321/s_curpar.inc"
#include "geant321/s_result.inc"
#include "geant321/s_mat.inc"
#include "geant321/s_event.inc"
#include "geant321/s_prntfl.inc"
#include "geant321/s_errcom.inc"
#include "geant321/s_blank.inc"
C

#endif
