*
* $Id: s_mat.inc 220 2007-11-19 16:08:06Z rdm $
*
* $Log: s_mat.inc,v $
* Revision 1.1.1.1  2002/06/16 15:18:38  hristov
* Separate distribution  of Geant3
*
* Revision 1.1.1.1  1999/05/18 15:55:17  fca
* AliRoot sources
*
* Revision 1.1.1.1  1995/10/24 10:20:44  cernlib
* Geant
*
*
#ifndef CERNLIB_GEANT321_S_MAT_INC
#define CERNLIB_GEANT321_S_MAT_INC
*
*
* s_mat.inc
*
      COMMON/MAT   / LMAT,
     *               DEN(21),RADLTH(21),ATNO(21),ZNO(21),ABSL(21),
     *               CDEN(21),MDEN(21),X0DEN(21),X1DEN(21),RION(21),
     *               MATID(21),MATID1(21,24),PARMAT(21,10),
     *               IFRAT,IFRAC(21),FRAC1(21,10),DEN1(21,10),
     *               ATNO1(21,10),ZNO1(21,10)
C

#endif
