*
* $Id: bkfoparq.inc 220 2007-11-19 16:08:06Z rdm $
*
* $Log: bkfoparq.inc,v $
* Revision 1.1.1.1  2002/06/16 15:18:49  hristov
* Separate distribution  of Geant3
*
* Revision 1.1.1.1  1999/05/18 15:55:27  fca
* AliRoot sources
*
* Revision 1.1.1.1  1996/03/06 10:46:56  mclareni
* Zebra
*
*
#ifndef CERNLIB_ZEBRA_BKFOPARQ_INC
#define CERNLIB_ZEBRA_BKFOPARQ_INC
*
*  BANK FORMAT PARAMETERS  (IO CHARACERISTIC)
*
* bkfoparq.inc
*
      PARAMETER(IFOUNQ=0,IFOBIQ=1,IFOINQ=2,IFOFLQ=3,IFODOQ=4)
      PARAMETER(IFOHOQ=5,IFOSEQ=7,IFONAQ=9,IFOLIQ=11,JFOSEQ=16)

#endif
