*
* $Id: eqlqform.inc 220 2007-11-19 16:08:06Z rdm $
*
* $Log: eqlqform.inc,v $
* Revision 1.1.1.1  2002/06/16 15:18:49  hristov
* Separate distribution  of Geant3
*
* Revision 1.1.1.1  1999/05/18 15:55:27  fca
* AliRoot sources
*
* Revision 1.1.1.1  1996/03/06 10:46:53  mclareni
* Zebra
*
*
#ifndef CERNLIB_ZEBRA_EQLQFORM_INC
#define CERNLIB_ZEBRA_EQLQFORM_INC
*
*       MZFORM - 1 structural link
*
* eqlqform.inc
*
                   EQUIVALENCE (LQFORM,LQSYSS(5))

#endif
