*
* $Id: eqlqmst.inc 220 2007-11-19 16:08:06Z rdm $
*
* $Log: eqlqmst.inc,v $
* Revision 1.1.1.1  2002/06/16 15:18:49  hristov
* Separate distribution  of Geant3
*
* Revision 1.1.1.1  1999/05/18 15:55:27  fca
* AliRoot sources
*
* Revision 1.1.1.1  1996/03/06 10:46:53  mclareni
* Zebra
*
*
#ifndef CERNLIB_ZEBRA_EQLQMST_INC
#define CERNLIB_ZEBRA_EQLQMST_INC
*
*        MZ - 1 structural link (only)
*
* eqlqmst.inc
*
                   DIMENSION    LQMST(9)
                   EQUIVALENCE (LQMST(1),LQSYSS(2))

#endif
