*
* $Id: qstore.inc 220 2007-11-19 16:08:06Z rdm $
*
* $Log: qstore.inc,v $
* Revision 1.1.1.1  2002/06/16 15:18:50  hristov
* Separate distribution  of Geant3
*
* Revision 1.1.1.1  1999/05/18 15:55:27  fca
* AliRoot sources
*
* Revision 1.1.1.1  1996/03/06 10:46:53  mclareni
* Zebra
*
*
#ifndef CERNLIB_ZEBRA_QSTORE_INC
#define CERNLIB_ZEBRA_QSTORE_INC
*
*
* qstore.inc
*
      IF (JBYT(IXSTOR,27,6).NE.JQSTOR)  CALL MZSDIV (IXSTOR,-7)
*  -------------   for ZEBRA MZ   ------------------------------

#endif
