*
* $Id: quest.inc 220 2007-11-19 16:08:06Z rdm $
*
* $Log: quest.inc,v $
* Revision 1.1.1.1  2002/06/16 15:18:50  hristov
* Separate distribution  of Geant3
*
* Revision 1.1.1.1  1999/05/18 15:55:27  fca
* AliRoot sources
*
* Revision 1.1.1.1  1996/03/06 10:46:52  mclareni
* Zebra
*
*
#ifndef CERNLIB_ZEBRA_QUEST_INC
#define CERNLIB_ZEBRA_QUEST_INC
*
*
* quest.inc
*
      COMMON /QUEST/ IQUEST(100)

#endif
