*
* $Id: qversion.inc 220 2007-11-19 16:08:06Z rdm $
*
* $Log: qversion.inc,v $
* Revision 1.1.1.1  2002/06/16 15:18:50  hristov
* Separate distribution  of Geant3
*
* Revision 1.1.1.1  1999/05/18 15:55:27  fca
* AliRoot sources
*
* Revision 1.2  1996/04/18 16:15:27  mclareni
* Incorporate changes from J.Zoll for version 3.77
*
* Revision 1.1.1.1  1996/03/06 10:46:55  mclareni
* Zebra
*
*
#ifndef CERNLIB_ZEBRA_QVERSION_INC
#define CERNLIB_ZEBRA_QVERSION_INC
*
*    VERSION NUMBER
*
* qversion.inc
*
      QVERSN = 3.77

#endif
