*
* $Id: rzckey.inc 220 2007-11-19 16:08:06Z rdm $
*
* $Log: rzckey.inc,v $
* Revision 1.1.1.1  2002/06/16 15:18:50  hristov
* Separate distribution  of Geant3
*
* Revision 1.1.1.1  1999/05/18 15:55:27  fca
* AliRoot sources
*
* Revision 1.1.1.1  1996/03/06 10:46:55  mclareni
* Zebra
*
*
#ifndef CERNLIB_ZEBRA_RZCKEY_INC
#define CERNLIB_ZEBRA_RZCKEY_INC
*
*
* rzckey.inc
*
      COMMON/RZCKEY/IHEAD(3),KEY(100),KEY2(100),KEYDUM(50)
C

#endif
