*
* $Id: rzcl.inc 220 2007-11-19 16:08:06Z rdm $
*
* $Log: rzcl.inc,v $
* Revision 1.1.1.1  2002/06/16 15:18:50  hristov
* Separate distribution  of Geant3
*
* Revision 1.1.1.1  1999/05/18 15:55:27  fca
* AliRoot sources
*
* Revision 1.1.1.1  1996/03/06 10:46:55  mclareni
* Zebra
*
*
#ifndef CERNLIB_ZEBRA_RZCL_INC
#define CERNLIB_ZEBRA_RZCL_INC
*
*
* rzcl.inc
*
#include "zebra/mqsys.inc"
C
#include "zebra/rzclxx.inc"
#include "zebra/eqlqr.inc"
C
*  -------------   for ZEBRA CQ   ------------------------------

#endif
