*
* $Id: zunit.inc 220 2007-11-19 16:08:06Z rdm $
*
* $Log: zunit.inc,v $
* Revision 1.1.1.1  2002/06/16 15:18:50  hristov
* Separate distribution  of Geant3
*
* Revision 1.1.1.1  1999/05/18 15:55:28  fca
* AliRoot sources
*
* Revision 1.1.1.1  1996/03/06 10:46:52  mclareni
* Zebra
*
*
#ifndef CERNLIB_ZEBRA_ZUNIT_INC
#define CERNLIB_ZEBRA_ZUNIT_INC
*
*                Logical Unit Numbers
*
* zunit.inc
*
      COMMON /ZUNIT/ IQREAD,IQPRNT,IQPR2,IQLOG,IQPNCH,IQTTIN,IQTYPE
      COMMON /ZUNITZ/IQDLUN,IQFLUN,IQHLUN,  NQUSED

#endif
