*
* $Id: bknmparq.inc 220 2007-11-19 16:08:06Z rdm $
*
* $Log: bknmparq.inc,v $
* Revision 1.1.1.1  2002/06/16 15:18:49  hristov
* Separate distribution  of Geant3
*
* Revision 1.1.1.1  1999/05/18 15:55:27  fca
* AliRoot sources
*
* Revision 1.1.1.1  1996/03/06 10:46:56  mclareni
* Zebra
*
*
#ifndef CERNLIB_ZEBRA_BKNMPARQ_INC
#define CERNLIB_ZEBRA_BKNMPARQ_INC
*
*  BANK NAME PARAMETERS (MZLIFT)
*
* bknmparq.inc
*
      PARAMETER(NNMBKQ=5,MNMIDQ=1,MNMNLQ=MNMIDQ+1)
      PARAMETER(MNMNSQ=MNMNLQ+1,MNMNDQ=MNMNSQ+1,MNMIOQ=MNMNDQ+1)

#endif
