*
* $Id: divparq.inc 220 2007-11-19 16:08:06Z rdm $
*
* $Log: divparq.inc,v $
* Revision 1.1.1.1  2002/06/16 15:18:49  hristov
* Separate distribution  of Geant3
*
* Revision 1.1.1.1  1999/05/18 15:55:27  fca
* AliRoot sources
*
* Revision 1.1.1.1  1996/03/06 10:46:57  mclareni
* Zebra
*
*
#ifndef CERNLIB_ZEBRA_DIVPARQ_INC
#define CERNLIB_ZEBRA_DIVPARQ_INC
*
*DIVISION PARAMETERS
*
* divparq.inc
*
      PARAMETER(JDVBFQ=1,NDVBFQ=1,IDVFWQ=0,IDVBWQ=1)
      PARAMETER(IDVUSQ=1,IDVLGQ=2,IDVPAQ=3,IDVSYQ=4)
      PARAMETER(JDVIDQ=1,NDVIDQ=20)
      PARAMETER(JDVUSQ=21,JDVLGQ=22,JDVPAQ=23,JDVSYQ=24)
      PARAMETER(MDVLWQ=1,MDVHGQ=2)

#endif
