*
* $Id: fzcx.inc 220 2007-11-19 16:08:06Z rdm $
*
* $Log: fzcx.inc,v $
* Revision 1.1.1.1  2002/06/16 15:18:49  hristov
* Separate distribution  of Geant3
*
* Revision 1.1.1.1  1999/05/18 15:55:27  fca
* AliRoot sources
*
* Revision 1.1.1.1  1996/03/06 10:46:54  mclareni
* Zebra
*
*
#ifndef CERNLIB_ZEBRA_FZCX_INC
#define CERNLIB_ZEBRA_FZCX_INC
*
*
* fzcx.inc
*
      COMMON /FZCX/  LUNX,LUNNX,IXDIVX,LTEMPX,IEVFLX
     +,              MSTATX,MEDIUX,IFIFOX,IDAFOX,IACMOX,IUPAKX
     +,              IADOPX,IACTVX,INCBPX,LOGLVX,MAXREX
     +,              NWFILX,ISTENX,LTEXTX,ICOPYX
     +,              LBPARX,L4STOX,L4STAX,L4CURX,L4ENDX
     +,              MODTBX,JFLGAX,IOPTXD,IOPTXI,IOPTXS,IOPTXZ,IOPTXM
     +,              IOPTXL,IOPTXN,IOPTXP,IOPTXF,IOPTXT,IOPTXV(2)
     +,              IDX(2),IPILX(4),NWTXX,NWSEGX,NWTABX,NWBKX,LENTRX
     +,              NWUHCX,IOCHX(16),NWUHX,NWIOX,LUHEAX,JRUNX

#endif
