*
* $Id: mzcl.inc 220 2007-11-19 16:08:06Z rdm $
*
* $Log: mzcl.inc,v $
* Revision 1.1.1.1  2002/06/16 15:18:49  hristov
* Separate distribution  of Geant3
*
* Revision 1.1.1.1  1999/05/18 15:55:27  fca
* AliRoot sources
*
* Revision 1.1.1.1  1996/03/06 10:46:53  mclareni
* Zebra
*
*
#ifndef CERNLIB_ZEBRA_MZCL_INC
#define CERNLIB_ZEBRA_MZCL_INC
*
*                 Lift Name parameters
*
* mzcl.inc
*
      COMMON /MZCL/  NQLN,NQLS,NQNIO,NQID,NQNL,NQNS,NQND,NQIOCH(16)
     +,              LQSUP,NQBIA, NQIOSV(3)

#endif
