*
* $Id: rzclun.inc 220 2007-11-19 16:08:06Z rdm $
*
* $Log: rzclun.inc,v $
* Revision 1.1.1.1  2002/06/16 15:18:50  hristov
* Separate distribution  of Geant3
*
* Revision 1.1.1.1  1999/05/18 15:55:27  fca
* AliRoot sources
*
* Revision 1.1.1.1  1996/03/06 10:46:54  mclareni
* Zebra
*
*
#ifndef CERNLIB_ZEBRA_RZCLUN_INC
#define CERNLIB_ZEBRA_RZCLUN_INC
*
*
* rzclun.inc
*
      COMMON /RZCLUN/LUN,LREC,ISAVE,IMODEX,IRELAT,NHPWD,IHPWD(2)
     +,              IZRECL,IMODEC,IMODEH
C

#endif
