*
* $Id: rzcout.inc 220 2007-11-19 16:08:06Z rdm $
*
* $Log: rzcout.inc,v $
* Revision 1.1.1.1  2002/06/16 15:18:50  hristov
* Separate distribution  of Geant3
*
* Revision 1.1.1.1  1999/05/18 15:55:27  fca
* AliRoot sources
*
* Revision 1.1.1.1  1996/03/06 10:46:55  mclareni
* Zebra
*
*
#ifndef CERNLIB_ZEBRA_RZCOUT_INC
#define CERNLIB_ZEBRA_RZCOUT_INC
*
*
* rzcout.inc
*
      COMMON /RZCOUT/IP1,IR1,IR2,IROUT,IRLOUT,IOPTRR
C

#endif
