*
* $Id: eva0.inc 220 2007-11-19 16:08:06Z rdm $
*
* $Log: eva0.inc,v $
* Revision 1.1.1.1  2002/06/16 15:18:38  hristov
* Separate distribution  of Geant3
*
* Revision 1.1.1.1  1999/05/18 15:55:16  fca
* AliRoot sources
*
* Revision 1.1.1.1  1995/10/24 10:20:38  cernlib
* Geant
*
*
#ifndef CERNLIB_GEANT321_EVA0_INC
#define CERNLIB_GEANT321_EVA0_INC
*
*
* eva0.inc
*
*                                                                      *
*=== eva0 =============================================================*
*                                                                      *
      COMMON / FKEVA0 / Y0, B0, P0 (1001), P1 (1001), P2 (1001),
     *                FLA (6), FLZ (6), RHO (6), OMEGA (6), EXMASS (6),
     *                CAM2 (130), CAM3 (200), CAM4 (130), CAM5 (200),
     *                T (4,7), RMASS (297), ALPH (297), BET (297),
     *                WAPS (250,11), APRIME (250), IA (6), IZ (6)
 

#endif
