*
* $Id: gcsetf.inc 220 2007-11-19 16:08:06Z rdm $
*
* $Log: gcsetf.inc,v $
* Revision 1.1.1.1  2002/06/16 15:18:38  hristov
* Separate distribution  of Geant3
*
* Revision 1.1.1.1  1999/05/18 15:55:16  fca
* AliRoot sources
*
* Revision 1.1.1.1  1995/10/24 10:20:42  cernlib
* Geant
*
*
#ifndef CERNLIB_GEANT321_GCSETF_INC
#define CERNLIB_GEANT321_GCSETF_INC
*
*
* gcsetf.inc
*
      COMMON/GCADII/NPLACE,NUNIT1,N1,NUNIT2
*
      COMMON/GCADIC/BLKSTR,JVSTR
      CHARACTER*500 BLKSTR
      CHARACTER*80  JVSTR
*

#endif
