*
* $Id: gtbank.inc 220 2007-11-19 16:08:06Z rdm $
*
* $Log: gtbank.inc,v $
* Revision 1.1.1.1  2002/06/16 15:18:38  hristov
* Separate distribution  of Geant3
*
* Revision 1.1.1.1  1999/05/18 15:55:16  fca
* AliRoot sources
*
* Revision 1.1.1.1  1995/10/24 10:20:31  cernlib
* Geant
*
*
#ifndef CERNLIB_GEANT321_GTBANK_INC
#define CERNLIB_GEANT321_GTBANK_INC
*
*
* gtbank.inc
*
#if !defined(CERNLIB_INCLUDE)
      INTEGER IQ,LQ,NZEBRA,IXSTOR,IXDIV,IXCONS,LMAIN,LR1,JCG
      INTEGER KWBANK,KWWORK,IWS
      REAL GVERSN,ZVERSN,FENDQ,WS,Q
C
#endif

#endif
