*
* $Id: gtrayt.inc 220 2007-11-19 16:08:06Z rdm $
*
* $Log: gtrayt.inc,v $
* Revision 1.1.1.1  2002/06/16 15:18:38  hristov
* Separate distribution  of Geant3
*
* Revision 1.1.1.1  1999/05/18 15:55:16  fca
* AliRoot sources
*
* Revision 1.1.1.1  1995/10/24 10:20:36  cernlib
* Geant
*
*
#ifndef CERNLIB_GEANT321_GTRAYT_INC
#define CERNLIB_GEANT321_GTRAYT_INC
*
*
* gtrayt.inc
*
#if !defined(CERNLIB_INCLUDE)
      INTEGER INTEN,IOMBRA,IXYFLA,NOFLAG
      REAL XLPOS,YLPOS,ZLPOS,XLDIR,YLDIR,ZLDIR,APFLAH,
     +     CCXX,CCYY,CCZZ,BOFLAG,APFLAG,
     +     XCOSXS,YCOSYS,ZCOSZS,VDX,VDY,VDZ,SSLENG,
     +     XPINTS,YPINTS,ZPINTS,FPINTX,FPINTY,FPINTZ,
     +     AROTS,ZROTS,RRR
#endif

#endif
