*
* $Id: gtscal.inc 220 2007-11-19 16:08:06Z rdm $
*
* $Log: gtscal.inc,v $
* Revision 1.1.1.1  2002/06/16 15:18:38  hristov
* Separate distribution  of Geant3
*
* Revision 1.1.1.1  1999/05/18 15:55:16  fca
* AliRoot sources
*
* Revision 1.1.1.1  1995/10/24 10:20:34  cernlib
* Geant
*
*
#ifndef CERNLIB_GEANT321_GTSCAL_INC
#define CERNLIB_GEANT321_GTSCAL_INC
*
*
* gtscal.inc
*
#if !defined(CERNLIB_INCLUDE)
      INTEGER MXSLNK, ISLINK, LSLAST, LSCAN, LSTEMP, LSPARA, LSERAY
*
#endif

#endif
