*
* $Id: pawct.inc 220 2007-11-19 16:08:06Z rdm $
*
* $Log: pawct.inc,v $
* Revision 1.1.1.1  2002/06/16 15:18:38  hristov
* Separate distribution  of Geant3
*
* Revision 1.1.1.1  1999/05/18 15:55:17  fca
* AliRoot sources
*
* Revision 1.1.1.1  1995/10/24 10:20:35  cernlib
* Geant
*
*
#ifndef CERNLIB_GEANT321_PAWCT_INC
#define CERNLIB_GEANT321_PAWCT_INC
*
*
* pawct.inc
*
#if !defined(CERNLIB_INCLUDE)
      INTEGER NWPAW,IXPAWC,IHBOOK,IXHIGZ,IXKUIP,IFENCE,LLMAIN,IQQ,LQQ
      REAL WWS,QQ
#endif

#endif
