*
* $Id: s_blank.inc 220 2007-11-19 16:08:06Z rdm $
*
* $Log: s_blank.inc,v $
* Revision 1.1.1.1  2002/06/16 15:18:38  hristov
* Separate distribution  of Geant3
*
* Revision 1.1.1.1  1999/05/18 15:55:17  fca
* AliRoot sources
*
* Revision 1.1.1.1  1995/10/24 10:20:43  cernlib
* Geant
*
*
#ifndef CERNLIB_GEANT321_S_BLANK_INC
#define CERNLIB_GEANT321_S_BLANK_INC
*
*        *** NVE 09-FEB-1988 ***
*
* s_blank.inc
*
      PARAMETER (MXGKPV=MXGKGH)
      COMMON /VECUTY/ PV(10,MXGKPV)
C

#endif
