*
* $Id: s_kginit.inc 220 2007-11-19 16:08:06Z rdm $
*
* $Log: s_kginit.inc,v $
* Revision 1.1.1.1  2002/06/16 15:18:38  hristov
* Separate distribution  of Geant3
*
* Revision 1.1.1.1  1999/05/18 15:55:17  fca
* AliRoot sources
*
* Revision 1.1.1.1  1995/10/24 10:20:44  cernlib
* Geant
*
*
#ifndef CERNLIB_GEANT321_S_KGINIT_INC
#define CERNLIB_GEANT321_S_KGINIT_INC
*
*       *** NVE 09-FEB-1988 ***
*
* s_kginit.inc
*
C --- INITIALIZATION FLAGS FOR VARIOUS GHEISHA ROUTINES ---
      COMMON /KGINIT/ KGINIT(50)
C

#endif
